"""admin_settings

Revision ID: 6a93e1eb6780
Revises: 
Create Date: 2026-06-17 07:39:23.695752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a93e1eb6780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('blog', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('blog', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('blog', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'writer', ['created_by'], ['id'])
    op.create_foreign_key(None, 'blog', 'writer', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'blog', 'writer', ['updated_by'], ['id'])
    op.alter_column('image', 'data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'deleted_by')
    op.drop_column('blog', 'deleted_at')
    op.drop_column('blog', 'updated_by')
    op.drop_column('blog', 'created_by')
    # ### end Alembic commands ###
