"""admin roles

Revision ID: a73f6eb63936
Revises: 446f4f176550
Create Date: 2026-07-01 06:11:31.737512

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a73f6eb63936'
down_revision: Union[str, Sequence[str], None] = '446f4f176550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('writer_role',
                    sa.Column('writer_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.ForeignKeyConstraint(['writer_id'], ['writer.id'], ),
                    sa.PrimaryKeyConstraint('writer_id', 'role_id')
                    )
    op.alter_column('image', 'data',
                    existing_type=mysql.MEDIUMBLOB(),
                    type_=sa.LargeBinary(length=16777215),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'data',
                    existing_type=sa.LargeBinary(length=16777215),
                    type_=mysql.MEDIUMBLOB(),
                    nullable=False)
    op.drop_table('writer_role')
    op.drop_table('role')
    # ### end Alembic commands ###
